name: Publish to TestPyPI

on:
  workflow_dispatch:

jobs:
  publish-testpypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry repositories
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: Configure Poetry token
        run: poetry config pypi-token.testpypi ${{ secrets.PYPI_TOKEN_TEST }}

      - name: Build package
        run: poetry build

      - name: Publish to TestPyPI
        run: poetry publish -r testpypi --no-interaction
