name: CD

on:
  workflow_run:
    workflows: ["Create Tag and Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"

      - name: Build and Publish
        run: |
          poetry build
          poetry publish --no-interaction