name: Create Tag and Release Test

on:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from pyproject.toml
        id: extract_version
        run: |
          VERSION=$(grep -m 1 '^version =' pyproject.toml | cut -d '"' -f2)
          VERSION_TAG="v$(echo "$VERSION" | sed 's/\./_/g')"
          echo "version_tag=$VERSION_TAG" >> "$GITHUB_OUTPUT"

      - name: Show extracted version
        run: |
          echo "Tag will be: ${{ steps.extract_version.outputs.version_tag }}"

      - name: Create git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

          git tag "${{ steps.extract_version.outputs.version_tag }}"
          git push origin "${{ steps.extract_version.outputs.version_tag }}"
